Algoritmo "Questão 05"
//Fazer um programa que pergunte o salário de um funcionário
//e apresente este salário com um aumento de 15%
Var
// Seção de Declarações das variáveis 
  x1,x2,x3 :real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    escreval (" Informe seu salário:")
    leia(x1)
    x2 <- (x1 * 15) / 100
    x3 <- x1 + x2
    escreval (" O aumento do salário foi ", x3)

Fimalgoritmo